version: '3.9'

services:
  app:
      container_name: app
      build:
          context: ./
          dockerfile: ./.docker/php/Dockerfile
      restart: unless-stopped
      tty: true
      volumes:
          - ./:/var/www/backend
          - ./.docker/php/ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
          - ./.docker/php/supervisord.conf:/etc/supervisor/supervisord.conf
      command: [ "/home/www/entry.sh" ]
      networks:
          - app-network

  nginx:
      container_name: nginx
      image: nginx:alpine
      ports:
          - "80:80"
          - "443:443"
          - "8080:8080"
      volumes:
          - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./.docker/nginx/${APP_ENV}:/etc/nginx/conf.d/
          - ./.docker/nginx/logs:/var/log/nginx
          - ./.docker/nginx/snippets:/etc/nginx/snippets
          - ./.docker/nginx/mime.types:/etc/nginx/mime.types
          - ./.docker/nginx/ssl:/etc/nginx/ssl
          - ./:/var/www/backend
          - ../apic-front:/var/www/front
      restart: unless-stopped
      depends_on:
          - app
      networks:
          - app-network

  database:
      container_name: db
      image: mysql:8.0.32
      volumes:
          - ./.docker/db/data:/var/lib/mysql:delegated
      command:
        --max_allowed_packet=250M
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
      environment:
          - MYSQL_DATABASE=${DB_DATABASE}
          - MYSQL_USER=${DB_USERNAME}
          - MYSQL_PASSWORD=${DB_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      ports:
          - ${DB_PORT}:3306
      restart: unless-stopped
      networks:
          - app-network

  elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
      ports:
          - "9200:9200"
          - "9300:9300"
      environment:
          - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
          #- "ES_JAVA_OPTS=-Des.enforce.bootstrap.checks=true"
      volumes:
          - ./.docker/elasticsearch/logs:/var/log/elasticsearch
          - ./.docker/elasticsearch/data:/usr/share/elasticsearch/data:rw
          - ./.docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      networks:
          - app-network
      deploy:
          resources:
              limits:
                  cpus: '0.2'
                  memory: 700M
      restart: unless-stopped

networks:
    app-network:
        driver: bridge
